#!/bin/bash

export GOFLAGS="-tags=debug,sr"

if [ -f ~/.ssh/gitlab ]; then
	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/gitlab
else
	echo "Warning: ~/.ssh/gitlab key not found!"
fi


main (){
	session="$(sesh list -i -c | gum filter --limit 1 --no-sort --fuzzy --placeholder 'Pick a project' --height 50 --prompt='⚡')"
	# session=$(sesh list -t -c | fzf --height 40% --reverse --border-label ' sesh ' --border --prompt '⚡  ')
	[[ -z "$session" ]] && return
	sesh connect $session
}

main $@
